# Generated by Django 3.0.3 on 2020-02-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='itle',
            new_name='title',
        ),
    ]
